app.name: Corgi Gift Delivery # var__app_name
app.frontend_base_href: corgi-delivery-app # var__frontend_base_href

server:
  port: 8080
  tomcat:
    max-connections: 100
    resource:
      allow-caching: true
  compression:
    enabled: true

spring:
  application:
    name: ${app.name:cogriTest}
  output:
    ansi:
      enabled: always
  jackson:
    time-zone: GMT+07:00

database:
  jdbcUrl: jdbc:h2:file:./dbdata/corgiGiftDelivery;DB_CLOSE_DELAY=-1
  username: sa
  password:
  driverClassName: org.h2.Driver

logging:
  file:
    name: logs/${app.name:cogriTest}.log
    path: logs/${app.name:cogriTest}.log
  pattern:
    dateformat: yyyy-MM-dd'T'HH:mm:ssXXX

  level:
    root: info
    org:
      springframework: info
    org.springframework.web: debug
    org.hibernate: debug
    tech:
      nmhillusion: DEBUG