server:
  port: 8080
  tomcat:
    max-connections: 100
    resource:
      allow-caching: true
  compression:
    enabled: true

spring:
  application:
    name: Slight Transportation
  output:
    ansi:
      enabled: always
  jackson:
    time-zone: GMT+07:00

database:
  jdbcUrl: jdbc:h2:file:./dbdata/slitran
  username: sa
  password:
  driverClassName: org.h2.Driver

logging:
  file:
    name: logs/sli-tran.log
    path: logs/sli-tran.log
  pattern:
    dateformat: yyyy-MM-dd'T'HH:mm:ssXXX

  level:
    root: info
    org:
      springframework: info
    org.springframework.web: debug
    org.hibernate: debug
    tech:
      nmhillusion: DEBUG