server:
  port: 8080
  tomcat:
    max-connections: 100
    resource:
      allow-caching: true
  compression:
    enabled: true

spring:
  application:
    name: Slight Transportation
  output:
    ansi:
      enabled: always
  jackson:
    time-zone: GMT+07:00

logging:
  file:
    name: sli-tran.log
    path: sli-tran.log
  pattern:
    dateformat: yyyy-MM-dd'T'HH:mm:ssXXX
    level:
      org:
        springframework: INFO
      tech:
        nmhillusion: DEBUG